# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.11.0
_src_path: gh:rostools/template-workshop
for_rostools: true
github_repo: data-viz-intro
github_user: rostools
workshop_type: r
